define GETPOT
  md_dir=${shell dirname $1}
  md_basename=${shell basename $1}
  pot_absdir=${shell cd pot && pwd}
  pot_absname=$(pot_absdir)/${shell basename $2}
  (cd ${md_dir} && \
     $(PO4AGETTEXTIZE) -f $3 -M utf-8 -m ${md_basename} -p ${pot_absname})
  @sed -i -e "s/CHARSET/ASCII/" ${pot_absname}
endef

define MSGPROC
  if test ! -f "$@"; then \
    msginit --no-translator -l ja \
     -i $1 -o $2 ;\
    sed -i \
           -e "/^\# PACKAGE.+/d" \
           -e "/Language-Team/s/none/matsuand個人翻訳/" \
           -e "/Content-Type/s/ASCII/UTF-8/" $2 ;\
  else \
    msgmerge -U $2 $1 ; \
    touch $2 ; \
  fi
endef

define PO4ATRANS
  if test "$3" = ""; then \
    $(PO4ATRANSLATE) -k 0 -w 100 -f $4 -M UTF-8 -m $1 -l $@ -p $2; \
  else \
    $(PO4ATRANSLATE) -k 0 -w 100 -f $4 -M UTF-8 -m $1 -l $@ -p $2 -A UTF-8 -a $3; \
  fi
endef
